### PR TITLE
Candidate duplicates

### PR DESCRIPTION
**Pull request by mlespiau**
Changes to quickAction.js please see notes https://github.com/opencats/OpenCATS/pull/168

### CODE REVIEW

**Comment by skrchnavy** [comment]
@mlespiau I don't understand why I don't see any notes in OpenCATS#168.
One main comment is to file js/quickAction.js, you changed it significant and I think it shall be merged as new PR (we will then merge it to our branch/PR). You can cherrypic commit 24886cf09b9c0f0ccbad85eb19b5445e3e870b73 .

Rest looks OK.

We will manage to move duplicates code to candidates, there is no special reason to have it as extra module, it is as @libregeek mentioned candidates functionality.

**Comment by mlespiau** [comment]
Hi @skrchnavy, Can you see my comments now? I've created a PR to your own branch show with code what I mean in my comments. You can merge if you want.

I agree with @libregeek to move the functionality to candidate module.

At last, I have not completed my review. I have more comments!!! Will do ASAP.

**Comment by mlespiau** [comment]
In order to view the comments maybe you need to choose view files tab: 

image

Regarding my changes, actually I implemented what I suggested based on your branch as an example and because I don't know your background and if you would follow my suggestions for having an extensible design.

**Comment by skrchnavy** [comment]
@mlespiau I merged your code into master and have it as PR opencats/OpenCATS#175

**Pull request closed without merging**
